Add composer package

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,20 @@
 version: 2
+install_composer: &install_composer
+  command: |
+    cd /tmp
+    EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+    ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+    then
+        >&2 echo 'ERROR: Invalid installer signature'
+        rm composer-setup.php
+        exit 1
+    fi
+    sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+    RESULT=$?
+    rm composer-setup.php
+    exit $RESULT
 jobs:
   build:
     machine:
@@ -6,6 +22,7 @@ jobs:
         version: 5.6.22
       services:
         - mysql
+        - composer
       environment:
         DB_HOST: 127.0.0.1
         DB_NAME: phalcon_base_project_test
@@ -27,6 +44,8 @@ jobs:
       - run: sudo echo 'date.timezone="UTC"' | sudo tee -a /etc/php/5.6/cli/php.ini
       - run: sudo echo "extension=/usr/lib/php/20131226/phalcon.so" | sudo tee -a /etc/php/5.6/apache2/conf.d/ext-phalcon.ini
       - run: sudo apt-get install ant
+      - run:
+        <<: *install_composer
       - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
       - run: composer install
       - run: mv env/.env.circleci env/.env.test
